{
 "title": "FLUIDOS Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage by Pods in Consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", node=~\"cloud\", namespace=~\"lower\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Pods in Provider1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", node=~\"(liqo-edge1)\", namespace=~\"lower\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Pods in Provider2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", node=~\"(liqo-edge2)\", namespace=~\"lower\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Packets by Pods in Consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n    rate(container_network_receive_packets_total{cluster=\"\",namespace=~\"lower\",node=~\"cloud\"}[$__rate_interval])\r\n  * on (cluster,namespace,pod) group_left ()\r\n    topk by (cluster,namespace,pod) (\r\n      1,\r\n      max by (cluster,namespace,pod) (kube_pod_info{host_network=\"false\"})\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Packets by Pods in Provider1",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n    rate(container_network_receive_packets_total{cluster=\"\",namespace=~\"lower\",node=~\"liqo-edge2\"}[$__rate_interval])\r\n  * on (cluster,namespace,pod) group_left ()\r\n    topk by (cluster,namespace,pod) (\r\n      1,\r\n      max by (cluster,namespace,pod) (kube_pod_info{host_network=\"false\"})\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Packets by Pods in Provider2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n    rate(container_network_receive_packets_total{cluster=\"\",namespace=~\"lower\",node=~\"liqo-edge1\"}[$__rate_interval])\r\n  * on (cluster,namespace,pod) group_left ()\r\n    topk by (cluster,namespace,pod) (\r\n      1,\r\n      max by (cluster,namespace,pod) (kube_pod_info{host_network=\"false\"})\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Pods in Consumer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=\"lower\",container!=\"\", image!=\"\", node=~\"cloud\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Pods in Provider1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=\"lower\",container!=\"\", image!=\"\", node=~\"liqo-edge1\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Pods in Provider1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=\"lower\",container!=\"\", image!=\"\", node=~\"liqo-edge2\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}