apiVersion: v1
kind: ServiceAccount
metadata:
  name: flavor-reader
  namespace: lower
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flavor-reader-role
  namespace: fluidos
rules:
  - apiGroups: ["nodecore.fluidos.eu"]
    resources: ["flavors"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flavor-reader-binding
  namespace: fluidos
subjects:
  - kind: ServiceAccount
    name: flavor-reader
    namespace: lower
roleRef:
  kind: Role
  name: flavor-reader-role
  apiGroup: rbac.authorization.k8s.io
