apiVersion: apps/v1
kind: Deployment
metadata:
  name: openpdc-higher
spec:
  selector:
    matchLabels:
      app: openpdc-high
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openpdc-high
    spec:
      initContainers:
      - name: openpdc-init
        image: riccardo170697/test-openpdc-init:13
        env:
            - name: DB_ROOTPASS
              valueFrom:
                secretKeyRef:
                  name: cluster1-secrets
                  key: root
            - name: DB_USER
              value: openpdch
            - name: DB_PASS
              value: password
            - name: DB_NAME
              value: higher
            - name: DB_PORT
              value: "3306"
            - name: DB_URL
              value: cluster1-haproxy.lower.svc.cluster.local
#            - name: SAMPLE_DATASET
#              value: "true"
        resources:
          requests:
            memory: 260M
            cpu: 800m
          limits:
            memory: 260M
            cpu: 900m
      containers:
      - name: openpdc
        image: claudious96/openpdc:latest
        env:
            - name: DB_USER
              value: openpdch
            - name: DB_PASS
              value: password
            - name: DB_NAME
              value: higher
            - name: DB_PORT
              value: "3306"
            - name: DB_URL
              value: cluster1-haproxy.lower.svc.cluster.local
            - name: NODE_ID
              value: 80104a12-a0de-435a-aa74-c93bade70a24
        livenessProbe:
          exec:
            command:
                - /bin/sh
                - liveness.sh
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - name: outputstream
          containerPort: 4712
          protocol: TCP
        - name: metadataws
          containerPort: 6151
          protocol: TCP
        - name: timeseriesws
          containerPort: 6152
          protocol: TCP
        - name: datapublisher
          containerPort: 6165
          protocol: TCP
        - name: console
          containerPort: 8500
          protocol: TCP
        resources:
          requests:
            memory: 260M
            cpu: 800m
          limits:
            memory: 260M
            cpu: 900m
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: liqo.io/type
                operator: DoesNotExist
---
apiVersion: v1
kind: Service
metadata:
  name: openpdc-high
spec:
  type: NodePort
  ports:
    - name: outputstream
      port: 4712
      nodePort: 30199
    - name: console
      port: 8500
      targetPort: 8500
      nodePort: 30185
    - name: datapublisher
      port: 6165
      targetPort: 6165
      nodePort: 30165
    - name: metadataws
      port: 6151
      targetPort: 6151
      nodePort: 30151
    - name: timeseriesws
      port: 6152
      targetPort: 6152
      nodePort: 30152
  selector:
    app: openpdc-high
